/**
 * Application-wide constants derived from the existing DB schema.
 * Role names and IDs match the seed data in security.sql.
 */

const ROLES = {
  ADMIN: 'ADMIN',
  POLICE: 'POLICE',
  JMO: 'JMO',
  MEDICAL_OFFICER: 'MEDICAL_OFFICER',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  GOVERNMENT_ANALYST: 'GOVERNMENT_ANALYST',
};

// These IDs match the SERIAL primary keys generated by the INSERT in security.sql
const ROLE_IDS = {
  ADMIN: 1,
  POLICE: 2,
  JMO: 3,
  MEDICAL_OFFICER: 4,
  LAB_TECHNICIAN: 5,
  GOVERNMENT_ANALYST: 6,
};

const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',    // Used for PENDING approval
  SUSPENDED: 'SUSPENDED',
};

const PERMISSIONS = {
  CREATE_CASE: 'CREATE_CASE',
  VIEW_CASE: 'VIEW_CASE',
  UPDATE_CASE: 'UPDATE_CASE',
  ADD_EVIDENCE: 'ADD_EVIDENCE',
  VIEW_EVIDENCE: 'VIEW_EVIDENCE',
  CREATE_EXAMINATION: 'CREATE_EXAMINATION',
  UPDATE_EXAMINATION: 'UPDATE_EXAMINATION',
  CREATE_MEDICAL_REPORT: 'CREATE_MEDICAL_REPORT',
  VIEW_MEDICAL_REPORT: 'VIEW_MEDICAL_REPORT',
  REQUEST_LAB_TEST: 'REQUEST_LAB_TEST',
  UPLOAD_LAB_RESULT: 'UPLOAD_LAB_RESULT',
  MANAGE_USERS: 'MANAGE_USERS',
};

// Human-readable labels for the signup form (UI value → DB role_name)
const SIGNUP_ROLES = [
  { label: 'Police Officer',            value: ROLES.POLICE },
  { label: 'Judicial Medical Officer',  value: ROLES.JMO },
  { label: 'Medical Officer',           value: ROLES.MEDICAL_OFFICER },
  { label: 'Laboratory Technician',     value: ROLES.LAB_TECHNICIAN },
  { label: 'Hospital Staff',            value: ROLES.GOVERNMENT_ANALYST },
];

// Roles that require a hospital_id on signup
const HOSPITAL_ROLES = [
  ROLES.JMO,
  ROLES.MEDICAL_OFFICER,
  ROLES.LAB_TECHNICIAN,
  ROLES.GOVERNMENT_ANALYST,
];

// Roles that require a station_id on signup
const STATION_ROLES = [ROLES.POLICE];

module.exports = {
  ROLES,
  ROLE_IDS,
  USER_STATUS,
  PERMISSIONS,
  SIGNUP_ROLES,
  HOSPITAL_ROLES,
  STATION_ROLES,
};
